login.url=https://172.26.100.115:8046/CareRating/auth/login
app.base.url=https://172.26.100.115:8046/CareRating/
api.base.uri=https://172.26.100.115:8046/

# Excel test data:
# 1) keep blank to use classpath testdata/login.xlsx
# 2) OR set an uploaded file path, e.g. C:/Users/Akshay/Downloads/login.xlsx
testdata.login.excel.path=
testdata.login.excel.sheet=Sheet1
